# pylint: disable=C0103
"""Migration file"""

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration file"""

    dependencies = [
        ("netbox_docker_plugin", "0033_host_operation"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE netbox_docker_plugin_container "
            + "ADD COLUMN IF NOT EXISTS log_driver character varying(32);",
            state_operations=[
                migrations.AddField(
                    model_name="container",
                    name="log_driver",
                    field=models.CharField(blank=True, max_length=32, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="container",
            name="ContainerID",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=1),
                    django.core.validators.MaxLengthValidator(limit_value=128),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="hostname",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=1),
                    django.core.validators.MaxLengthValidator(limit_value=256),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="public_port",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(limit_value=-1),
                    django.core.validators.MaxValueValidator(limit_value=65535),
                ]
            ),
        ),
        migrations.RunSQL(
            """
CREATE TABLE IF NOT EXISTS public.netbox_docker_plugin_logdriveroption
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    option_name character varying(255) NOT NULL,
    value character varying(4096) NOT NULL,
    container_id bigint NOT NULL,
    CONSTRAINT netbox_docker_plugin_logdriveroption_pkey PRIMARY KEY (id),
    CONSTRAINT netbox_docker_plugin_container_id_929d4dfe_fk_netbox_do FOREIGN KEY (container_id)
        REFERENCES public.netbox_docker_plugin_container (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS netbox_docker_plugin_logdriveroption_container_id_929d4dfe
    ON public.netbox_docker_plugin_logdriveroption USING btree
    (container_id ASC NULLS LAST);

CREATE UNIQUE INDEX IF NOT EXISTS netbox_docker_plugin_logdriveroption_unique_option_name_contain
    ON public.netbox_docker_plugin_logdriveroption USING btree
    (option_name ASC NULLS LAST, container_id ASC NULLS LAST);
            """,
            state_operations=[
                migrations.CreateModel(
                    name="LogDriverOption",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "option_name",
                            models.CharField(
                                max_length=255,
                                validators=[
                                    django.core.validators.MinLengthValidator(
                                        limit_value=1
                                    ),
                                    django.core.validators.MaxLengthValidator(
                                        limit_value=255
                                    ),
                                ],
                            ),
                        ),
                        (
                            "value",
                            models.CharField(
                                blank=True,
                                max_length=4096,
                                validators=[
                                    django.core.validators.MaxLengthValidator(
                                        limit_value=4096
                                    )
                                ],
                            ),
                        ),
                        (
                            "container",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="log_driver_options",
                                to="netbox_docker_plugin.container",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ("container", "option_name"),
                    },
                ),
                migrations.AddConstraint(
                    model_name="logdriveroption",
                    constraint=models.UniqueConstraint(
                        models.F("option_name"),
                        models.F("container"),
                        name="netbox_docker_plugin_logdriveroption_unique_option_name_container'",
                    ),
                ),
            ],
        ),
    ]
